### ISSUE TITLE
Model without architecture ?

### ISSUE THREAD

**Issue by jpthirumalai** [armiro/COVID-CXNet#10]
CheXNet_model.hdf5 - is that having the architecture / model

While trying load_model, facing following error
`
OSError: SavedModel file does not exist at: /content/drive/My Drive/xxxx/xxxx/chexnet/CheXNet_model.hdf5/{saved_model.pbtxt|saved_model.pb}`

using imports shown below
`
from tensorflow.keras.models import load_model, model_from_json`

**Comment by armiro** [comment]
@jpthirumalai if you are using Colab to test the code, could you please confirm that you have uploaded the `CheXNet_model.hdf5` file into the right address on your Google Drive? It seems like the problem is simply the wrong address for the `hdf5` file. I double-checked the file itself and everything was OK.
